/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_led_control                    21
#define gattdb_report_button                  23
#define gattdb_linear_string                  27
#define gattdb_linear_wheel                   31
#define gattdb_linear_sonic                   35
#define gattdb_angular_meas                   39
#define gattdb_settings                       43
#define gattdb_temperature_measurement        48
#define gattdb_temperature_type               51
#define gattdb_intermediate_temperature       53
#define gattdb_measurement_interval           56
#define gattdb_valid_range                    57
#define gattdb_ota_control                    60


#endif // __GATT_DB_H
